const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').replace('})();','window.testAPI={store,migrateData,validateImportPayload,exportPayload,commitGameData,saveResult,readDraftStore,renderModule,clearGameDraft,deleteAllData,parseParticipantNames,NEED_KEYS,NEED_QUESTIONS,NEED_PROFILES,NEED_COMBOS,DINNER};})();');
const STORE='insightGamesV1',DRAFT='insightGamesDraftsV1',EDIT='insightGamesTextEditsV1';
function app(t,seed={},hash=''){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(html,{url:'https://qa.example/'+hash,runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.CSS={escape:s=>s.replace(/[^\w-]/g,'\\$&')};w.confirm=()=>false;for(const [k,v] of Object.entries(seed))w.localStorage.setItem(k,v)}});
 t.after(()=>{dom.window.close();assert.deepEqual(errors,[],'No JavaScript errors')});
 const w=dom.window,d=w.document;return {w,d,api:w.testAPI,click:s=>{assert.ok(d.querySelector(s),'Missing '+s);d.querySelector(s).click()},fill:(s,v)=>{const e=d.querySelector(s);assert.ok(e,'Missing '+s);e.value=v;e.dispatchEvent(new w.Event('input',{bubbles:true}))},snapshot:()=>Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]))};
}
const result=(type='peak',data={moment:'vana tekst'})=>({id:'old-1',type,at:'2026-09-19T12:00:00.000Z',data});
test('legacy migration is idempotent, preserves full records and editor bytes',t=>{const old={results:[result()]},ed='{"custom":"minu tekst"}',a=app(t,{[STORE]:JSON.stringify(old),[EDIT]:ed});assert.equal(a.api.store().results[0].data.moment,'vana tekst');assert.equal(a.w.localStorage.getItem(EDIT),ed);assert.equal(JSON.stringify(a.api.migrateData(a.api.store())),JSON.stringify(a.api.store()));});
test('corrupt, unknown, and future stores are never overwritten',t=>{for(const raw of ['{broken','{}',JSON.stringify({schemaVersion:99,results:[]}),JSON.stringify({results:[{x:1}]})]){const a=app(t,{[STORE]:raw});assert.equal(a.w.localStorage.getItem(STORE),raw);assert.equal(a.api.saveResult('peak',{moment:'uus'}),false);assert.equal(a.w.localStorage.getItem(STORE),raw)}});
test('Pattern back, changed answers, sliders, all steps and refresh reach final result',t=>{let a=app(t,{},'#pattern');a.fill('#pfact','Esimene fakt');a.fill('#pstory','Esimene lugu');a.click('#pnext1');a.fill('#pbody','Õlad pinges');a.fill('#pint','4');a.click('#pback2');assert.equal(a.d.querySelector('#pfact').value,'Esimene fakt');assert.equal(a.d.querySelector('#pstory').value,'Esimene lugu');a.fill('#pfact','Muudetud fakt');a.click('#pnext1');assert.equal(a.d.querySelector('#pbody').value,'Õlad pinges');a.click('[data-e]');a.click('#pnext2');a.fill('#pmove','Vaikisin');a.fill('#ppay','Sain rahu');a.click('#pnext3');a.click('[data-need]');a.fill('#pcostn','Pinge');a.click('#pnext5');a.fill('#prepl','Küsin');a.fill('#pif','Kui märkan, siis küsin');a.fill('#pcf','8');a=app(t,a.snapshot(),'#pattern');assert.equal(a.d.querySelector('#prepl').value,'Küsin');a.click('#pfinish');assert.match(a.d.querySelector('#patbody').textContent,/Muudetud fakt/);a.click('#patsave');a.click('#patsave');assert.equal(a.api.store().results.length,1);assert.equal(a.api.store().results[0].data.confidence,8);assert.equal(a.api.store().results[0].data.value,'');});
test('needs previous answer is selected and replacement does not double-count',t=>{const a=app(t,{},'#needs');a.click('#nstart');a.click('[data-k]');a.click('#nback');assert.ok(a.d.querySelector('.choice.selected'));const other=a.d.querySelectorAll('[data-k]')[1];other.click();const state=a.api.readDraftStore().games.needs.state;assert.equal(Object.values(state.scores).reduce((x,y)=>x+y,0),1);assert.equal(state.answers.length,1);assert.equal(state.answers[0],other.dataset.k);});
test('values preserve question order and recompute score after answer edit',t=>{let a=app(t,{},'#values');[...a.d.querySelectorAll('[data-v]')].slice(0,8).forEach(b=>b.click());a.click('#vnext');const order=JSON.stringify(a.api.readDraftStore().games.values.state.roundPairs);a.click('.choice');a.click('#vback');assert.ok(a.d.querySelector('.choice.selected'));a.d.querySelectorAll('.choice')[1].click();a=app(t,a.snapshot(),'#values');const state=a.api.readDraftStore().games.values.state;assert.equal(JSON.stringify(state.roundPairs),order);assert.equal(Object.values(state.scores).reduce((x,y)=>x+y,0),1);});
test('appreciation confirms anonymously and restores behind a neutral screen',t=>{let a=app(t,{},'#appreciation');a.fill('#anames','Mari\nJüri');a.click('#astart');a.click('[data-n]');a.fill('#a1','Salajane tunnustus');a=app(t,a.snapshot(),'#appreciation');assert.ok(a.d.querySelector('#aresume'));assert.doesNotMatch(a.d.querySelector('#module').textContent,/Salajane tunnustus/);a.click('#aresume');a.click('#asend');a=app(t,a.snapshot(),'#appreciation');assert.doesNotMatch(a.d.querySelector('#module').textContent,/Salajane tunnustus/);assert.equal(a.api.readDraftStore().games.appreciation.state.entries.length,1);assert.equal(Object.hasOwn(a.api.readDraftStore().games.appreciation.state.entries[0],'author'),false);a.click('#areveal');assert.match(a.d.querySelector('#module').textContent,/Salajane tunnustus/);});
test('knowme self answer is hidden on refresh and saved with target context',t=>{let a=app(t,{},'#knowme');a.fill('#kmnames','QA Mari\nQA Jüri');a.click('#kmstart');a.click('[data-target]');a.click('#kmready');a.click('[data-self]');const answer=a.api.readDraftStore().games.knowme.state.selfAnswer;a=app(t,a.snapshot(),'#knowme');assert.ok(a.d.querySelector('#kmresume'));assert.ok(!a.d.querySelector('#module').textContent.includes(answer));a.click('#kmresume');a.click('#kmpass');a.click('[data-guesser]');a.click('[data-guess]');a.click('#kmsave');assert.equal(a.api.store().results[0].data.target,'QA Mari');});
test('roulette exhausts pack, does not repeat boundary, preserves count on refresh',t=>{let a=app(t,{},'#dinner');const cat=Object.keys(a.api.DINNER)[0],n=a.api.DINNER[cat].length;[...a.d.querySelectorAll('[data-cat]')].find(b=>b.dataset.cat===cat).click();let seen=[a.d.querySelector('#dq').textContent];for(let i=1;i<n;i++){a.click('#dnew');seen.push(a.d.querySelector('#dq').textContent)}assert.equal(new Set(seen).size,n);a.click('#dnew');assert.match(a.d.querySelector('#dq').textContent,/Kõik selle paki/);a=app(t,a.snapshot(),'#dinner');a.click('#dnew');assert.notEqual(a.d.querySelector('#dq').textContent,seen.at(-1));assert.match(a.d.querySelector('#dseen').textContent,new RegExp('^'+(n+1)+' '));});
test('wheel, state, peak, greece restore text and ranges on reopening',t=>{for(const [id,field] of [['wheel','#wn0'],['state','#curState'],['peak','#pmoment']]){const a=app(t,{},'#'+id);a.fill(field,'Pikk tekst '.repeat(50));const b=app(t,a.snapshot(),'#'+id);assert.equal(b.d.querySelector(field).value,'Pikk tekst '.repeat(50));assert.equal(b.api.store().results.length,0)}let a=app(t,{},'#greece');a.click('#gdraw');a.click('#gdone');a.fill('#gr','Väljakutse refleksioon');a.fill('#grange','9');a=app(t,a.snapshot(),'#greece');assert.equal(a.d.querySelector('#gr').value,'Väljakutse refleksioon');assert.equal(a.d.querySelector('#grange').value,'9');});
test('export delete import roundtrip keeps editor, rejects malformed import without changes',t=>{const a=app(t,{[EDIT]:'{"copy":"custom"}'},'#peak');a.fill('#pmoment','Taastatav mustand');a.api.saveResult('greece',{reflection:'ajalugu'});const exported=JSON.parse(JSON.stringify(a.api.exportPayload())),before=a.snapshot();for(const bad of [{},{...exported,schemaVersion:99},{...exported,completed:{schemaVersion:3,results:[{}]}},{...exported,drafts:{schemaVersion:99,games:{}}}])assert.throws(()=>a.api.validateImportPayload(bad));assert.deepEqual(a.snapshot(),before);a.api.deleteAllData();assert.deepEqual(a.snapshot(),before);a.w.confirm=()=>true;a.api.deleteAllData();assert.equal(a.api.store().results.length,0);assert.equal(a.w.localStorage.getItem(EDIT),'{"copy":"custom"}');const validated=a.api.validateImportPayload(exported);assert.ok(a.api.commitGameData(validated.completed,validated.drafts));assert.equal(a.api.store().results.length,1);assert.equal(a.api.readDraftStore().games.peak.fields.pmoment.value,'Taastatav mustand');});
test('quota failures do not report success or remove original bytes',t=>{const a=app(t,{[STORE]:JSON.stringify({schemaVersion:3,results:[result()]})},'#peak'),before=a.w.localStorage.getItem(STORE);a.w.Storage.prototype.setItem=function(){throw new Error('QuotaExceededError')};assert.equal(a.api.saveResult('peak',{moment:'uus'}),false);assert.equal(a.w.localStorage.getItem(STORE),before);assert.match(a.d.querySelector('#toast').textContent,/ebaõnnestus/);});
test('names enforce length, uniqueness and 2–8 players',t=>{const a=app(t);for(const names of ['Mari','Mari\n mari ',' \n ','x'.repeat(2000)+'\nJüri',Array.from({length:9},(_,i)=>'P'+i).join('\n')])assert.ok(a.api.parseParticipantNames(names).error);assert.equal(a.api.parseParticipantNames('Mari\nJüri').names.length,2)});
test('history displays escaped complete user text; repeated save does not rewrite older history',t=>{const a=app(t);a.api.saveResult('peak',{moment:'<img src=x onerror=alert(1)>täistekst'});a.api.renderModule('peak');a.api.saveResult('peak',{moment:'<img src=x onerror=alert(1)>täistekst'});assert.equal(a.api.store().results.length,2);a.api.renderModule('map');a.click('[data-view-result]');assert.equal(a.d.querySelector('#history img'),null);assert.match(a.d.querySelector('#history').textContent,/täistekst/);assert.equal(a.d.querySelector('#savedCount').textContent,'2 salvestatud tähelepanekut')});
test('all need profiles and all 15 pairs retain positive, risk and practical direction',t=>{const a=app(t);for(const key of a.api.NEED_KEYS){const p=a.api.NEED_PROFILES[key];assert.ok(p.positive&&p.danger&&p.balance)}assert.equal(Object.keys(a.api.NEED_COMBOS).length,15)});
