const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const {JSDOM,VirtualConsole}=require('jsdom');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8').replace('})();','window.testAPI={store,migrateData,validateImportPayload,exportPayload,commitGameData,importAllData,saveResult,readDraftStore,renderModule,clearGameDraft,deleteAllData,parseParticipantNames,NEED_KEYS,NEED_QUESTIONS,NEED_PROFILES,NEED_COMBOS,DINNER};})();');
const STORE='insightGamesV1',DRAFT='insightGamesDraftsV1',EDIT='insightGamesTextEditsV1';
test('roulette tailored followups cover every question, advance without repeats and restore',t=>{
 const source=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
 const tailored=JSON.parse(source.match(/const DINNER_FOLLOWUPS=(\{[\s\S]*?\n\});/)[1]);
 let a=app(t,{},'#dinner');
 assert.deepEqual(Object.keys(tailored),Object.values(a.api.DINNER).flat());
 assert.equal(a.d.querySelector('#ddeeper').disabled,true);
 for(const [q,followups] of Object.entries(tailored)){
  assert.equal(followups.length,2);assert.equal(new Set(followups).size,2);
  const cat=Object.entries(a.api.DINNER).find(([,qs])=>qs.includes(q))[0];
  a=app(t,{[DRAFT]:JSON.stringify({schemaVersion:2,games:{dinner:{state:{currentCat:cat,current:{cat,q}}}}})},'#dinner');
  a.click('#ddeeper');assert.ok(a.d.querySelector('#dfollow').textContent.endsWith(followups[0]));
  a=app(t,a.snapshot(),'#dinner');assert.ok(a.d.querySelector('#dfollow').textContent.endsWith(followups[0]));
  a.click('#ddeeper');assert.ok(a.d.querySelector('#dfollow').textContent.endsWith(followups[1]));assert.equal(a.d.querySelector('#ddeeper').disabled,true);
  a.click('#dnew');assert.equal(a.d.querySelector('#dfollow').textContent,'');assert.equal(a.d.querySelector('#ddeeper').disabled,false);
 }
});
function app(t,seed={},hash=''){
 const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
 const dom=new JSDOM(html,{url:'https://qa.example/'+hash,runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.scrollTo=()=>{};w.CSS={escape:s=>s.replace(/[^\w-]/g,'\\$&')};w.confirm=()=>false;for(const [k,v] of Object.entries(seed))w.localStorage.setItem(k,v)}});
 t.after(()=>{dom.window.close();assert.deepEqual(errors,[],'No JavaScript errors')});
 const w=dom.window,d=w.document;return {w,d,api:w.testAPI,click:s=>{assert.ok(d.querySelector(s),'Missing '+s);d.querySelector(s).click()},fill:(s,v)=>{const e=d.querySelector(s);assert.ok(e,'Missing '+s);e.value=v;e.dispatchEvent(new w.Event('input',{bubbles:true}))},snapshot:()=>Object.fromEntries(Object.keys(w.localStorage).map(k=>[k,w.localStorage.getItem(k)]))};
}
const result=(type='peak',data={moment:'vana tekst'})=>({id:'old-1',type,at:'2026-09-19T12:00:00.000Z',data});
test('legacy migration is idempotent, preserves full records and editor bytes',t=>{const old={results:[result()]},ed='{"custom":"minu tekst"}',a=app(t,{[STORE]:JSON.stringify(old),[EDIT]:ed});assert.equal(a.api.store().results[0].data.moment,'vana tekst');assert.equal(a.w.localStorage.getItem(EDIT),ed);assert.equal(JSON.stringify(a.api.migrateData(a.api.store())),JSON.stringify(a.api.store()));});
test('corrupt, unknown, and future stores are never overwritten',t=>{for(const raw of ['{broken','{}',JSON.stringify({schemaVersion:99,results:[]}),JSON.stringify({results:[{x:1}]})]){const a=app(t,{[STORE]:raw});assert.equal(a.w.localStorage.getItem(STORE),raw);assert.equal(a.api.saveResult('peak',{moment:'uus'}),false);assert.equal(a.w.localStorage.getItem(STORE),raw)}});
test('Pattern back, changed answers, sliders, all steps and refresh reach final result',t=>{let a=app(t,{},'#pattern');a.fill('#pfact','Esimene fakt');a.fill('#pstory','Esimene lugu');a.click('#pnext1');a.fill('#pbody','Õlad pinges');a.fill('#pint','4');a.click('#pback2');assert.equal(a.d.querySelector('#pfact').value,'Esimene fakt');assert.equal(a.d.querySelector('#pstory').value,'Esimene lugu');a.fill('#pfact','Muudetud fakt');a.click('#pnext1');assert.equal(a.d.querySelector('#pbody').value,'Õlad pinges');a.click('[data-e]');a.click('#pnext2');a.fill('#pmove','Vaikisin');a.fill('#ppay','Sain rahu');a.click('#pnext3');a.click('[data-need]');a.fill('#pcostn','Pinge');a.click('#pnext5');a.fill('#prepl','Küsin');a.fill('#pif','Kui märkan, siis küsin');a.fill('#pcf','8');a=app(t,a.snapshot(),'#pattern');assert.equal(a.d.querySelector('#prepl').value,'Küsin');a.click('#pfinish');assert.match(a.d.querySelector('#patbody').textContent,/Muudetud fakt/);a.click('#patsave');a.click('#patsave');assert.equal(a.api.store().results.length,1);assert.equal(a.api.store().results[0].data.confidence,8);assert.equal(a.api.store().results[0].data.value,'');});
test('needs previous answer is selected and replacement does not double-count',t=>{const a=app(t,{},'#needs');a.click('#nstart');a.click('[data-k]');a.click('#nback');assert.ok(a.d.querySelector('.choice.selected'));const other=a.d.querySelectorAll('[data-k]')[1];other.click();const state=a.api.readDraftStore().games.needs.state;assert.equal(Object.values(state.scores).reduce((x,y)=>x+y,0),1);assert.equal(state.answers.length,1);assert.equal(state.answers[0],other.dataset.k);});
test('values preserve question order and recompute score after answer edit',t=>{let a=app(t,{},'#values');[...a.d.querySelectorAll('[data-v]')].slice(0,8).forEach(b=>b.click());a.click('#vnext');const order=JSON.stringify(a.api.readDraftStore().games.values.state.roundPairs);a.click('.choice');a.click('#vback');assert.ok(a.d.querySelector('.choice.selected'));a.d.querySelectorAll('.choice')[1].click();a=app(t,a.snapshot(),'#values');const state=a.api.readDraftStore().games.values.state;assert.equal(JSON.stringify(state.roundPairs),order);assert.equal(Object.values(state.scores).reduce((x,y)=>x+y,0),1);});
test('appreciation confirms anonymously and restores behind a neutral screen',t=>{let a=app(t,{},'#appreciation');a.fill('#anames','Mari\nJüri');a.click('#astart');a.click('[data-n]');a.fill('#a1','Salajane tunnustus');a=app(t,a.snapshot(),'#appreciation');assert.ok(a.d.querySelector('#aresume'));assert.doesNotMatch(a.d.querySelector('#module').textContent,/Salajane tunnustus/);a.click('#aresume');a.click('#asend');a=app(t,a.snapshot(),'#appreciation');assert.doesNotMatch(a.d.querySelector('#module').textContent,/Salajane tunnustus/);assert.equal(a.api.readDraftStore().games.appreciation.state.entries.length,1);assert.equal(Object.hasOwn(a.api.readDraftStore().games.appreciation.state.entries[0],'author'),false);a.click('#areveal');assert.match(a.d.querySelector('#module').textContent,/Salajane tunnustus/);});
test('knowme self answer is hidden on refresh and saved with target context',t=>{let a=app(t,{},'#knowme');a.fill('#kmnames','QA Mari\nQA Jüri');a.click('#kmstart');a.click('[data-target]');a.click('#kmready');a.click('[data-self]');const answer=a.api.readDraftStore().games.knowme.state.selfAnswer;a=app(t,a.snapshot(),'#knowme');assert.ok(a.d.querySelector('#kmresume'));assert.ok(!a.d.querySelector('#module').textContent.includes(answer));a.click('#kmresume');a.click('#kmpass');a.click('[data-guesser]');a.click('[data-guess]');a.click('#kmsave');assert.equal(a.api.store().results[0].data.target,'QA Mari');});
test('roulette exhausts pack, does not repeat boundary, preserves count on refresh',t=>{let a=app(t,{},'#dinner');const cat=Object.keys(a.api.DINNER)[0],n=a.api.DINNER[cat].length;[...a.d.querySelectorAll('[data-cat]')].find(b=>b.dataset.cat===cat).click();let seen=[a.d.querySelector('#dq').textContent];for(let i=1;i<n;i++){a.click('#dnew');seen.push(a.d.querySelector('#dq').textContent)}assert.equal(new Set(seen).size,n);a.click('#dnew');assert.match(a.d.querySelector('#dq').textContent,/Kõik selle paki/);a=app(t,a.snapshot(),'#dinner');a.click('#dnew');assert.notEqual(a.d.querySelector('#dq').textContent,seen.at(-1));assert.match(a.d.querySelector('#dseen').textContent,new RegExp('^'+(n+1)+' '));});
test('wheel, state, peak, greece restore text and ranges on reopening',t=>{for(const [id,field] of [['wheel','#wn0'],['state','#curState'],['peak','#pmoment']]){const a=app(t,{},'#'+id);a.fill(field,'Pikk tekst '.repeat(50));const b=app(t,a.snapshot(),'#'+id);assert.equal(b.d.querySelector(field).value,'Pikk tekst '.repeat(50));assert.equal(b.api.store().results.length,0)}let a=app(t,{},'#greece');a.click('#gdraw');a.click('#gdone');a.fill('#gr','Väljakutse refleksioon');a.fill('#grange','9');a=app(t,a.snapshot(),'#greece');assert.equal(a.d.querySelector('#gr').value,'Väljakutse refleksioon');assert.equal(a.d.querySelector('#grange').value,'9');});
test('export delete import roundtrip keeps editor, rejects malformed import without changes',t=>{const a=app(t,{[EDIT]:'{"copy":"custom"}'},'#peak');a.fill('#pmoment','Taastatav mustand');a.api.saveResult('greece',{reflection:'ajalugu'});const exported=JSON.parse(JSON.stringify(a.api.exportPayload())),before=a.snapshot();for(const bad of [{},{...exported,schemaVersion:99},{...exported,completed:{schemaVersion:3,results:[{}]}},{...exported,drafts:{schemaVersion:99,games:{}}}])assert.throws(()=>a.api.validateImportPayload(bad));assert.deepEqual(a.snapshot(),before);a.api.deleteAllData();assert.deepEqual(a.snapshot(),before);a.w.confirm=()=>true;a.api.deleteAllData();assert.equal(a.api.store().results.length,0);assert.equal(a.w.localStorage.getItem(EDIT),'{"copy":"custom"}');const validated=a.api.validateImportPayload(exported);assert.ok(a.api.commitGameData(validated.completed,validated.drafts));assert.equal(a.api.store().results.length,1);assert.equal(a.api.readDraftStore().games.peak.fields.pmoment.value,'Taastatav mustand');});
test('quota failures do not report success or remove original bytes',t=>{const a=app(t,{[STORE]:JSON.stringify({schemaVersion:3,results:[result()]})},'#peak'),before=a.w.localStorage.getItem(STORE);a.w.Storage.prototype.setItem=function(){throw new Error('QuotaExceededError')};assert.equal(a.api.saveResult('peak',{moment:'uus'}),false);assert.equal(a.w.localStorage.getItem(STORE),before);assert.match(a.d.querySelector('#toast').textContent,/ebaõnnestus/);});
test('names enforce length, uniqueness and 2–8 players',t=>{const a=app(t);for(const names of ['Mari','Mari\n mari ',' \n ','x'.repeat(2000)+'\nJüri',Array.from({length:9},(_,i)=>'P'+i).join('\n')])assert.ok(a.api.parseParticipantNames(names).error);assert.equal(a.api.parseParticipantNames('Mari\nJüri').names.length,2)});
test('history displays escaped complete user text; repeated save does not rewrite older history',t=>{const a=app(t);a.api.saveResult('peak',{moment:'<img src=x onerror=alert(1)>täistekst'});a.api.renderModule('peak');a.api.saveResult('peak',{moment:'<img src=x onerror=alert(1)>täistekst'});assert.equal(a.api.store().results.length,2);a.api.renderModule('map');a.click('[data-view-result]');assert.equal(a.d.querySelector('#history img'),null);assert.match(a.d.querySelector('#history').textContent,/täistekst/);assert.equal(a.d.querySelector('#savedCount').textContent,'2 salvestatud tähelepanekut')});
test('all need profiles and all 15 pairs retain positive, risk and practical direction',t=>{const a=app(t);for(const key of a.api.NEED_KEYS){const p=a.api.NEED_PROFILES[key];assert.ok(p.positive&&p.danger&&p.balance)}assert.equal(Object.keys(a.api.NEED_COMBOS).length,15)});
test('future or malformed drafts stay byte-for-byte intact',t=>{for(const raw of ['{bad',JSON.stringify({schemaVersion:99,games:{}}),JSON.stringify({schemaVersion:2,games:{needs:{state:{idx:500}}}})]){const a=app(t,{[DRAFT]:raw},'#needs');a.click('#nstart');assert.equal(a.w.localStorage.getItem(DRAFT),raw)}});
test('interrupted multi-key transaction restores both old stores on startup',t=>{const before={[STORE]:JSON.stringify({schemaVersion:3,results:[result()]}),[DRAFT]:JSON.stringify({schemaVersion:2,games:{peak:{fields:{pmoment:{value:'vana mustand'}}}}})},a=app(t,{...before,[STORE]:JSON.stringify({schemaVersion:3,results:[]}),'insightGamesTransactionV1':JSON.stringify(before)});assert.equal(a.api.store().results.length,1);assert.equal(a.api.readDraftStore().games.peak.fields.pmoment.value,'vana mustand');assert.equal(a.w.localStorage.getItem('insightGamesTransactionV1'),null)});
test('second import write failure rolls back without changing editor or old data',t=>{const a=app(t,{[STORE]:JSON.stringify({schemaVersion:3,results:[result()]})}),old=a.snapshot(),set=a.w.Storage.prototype.setItem;let fail=true;a.w.Storage.prototype.setItem=function(k,v){if(k===DRAFT&&fail){fail=false;throw Error('quota')}return set.call(this,k,v)};assert.equal(a.api.commitGameData({schemaVersion:3,results:[]},{schemaVersion:2,games:{}}),false);assert.deepEqual(a.snapshot(),old)});
test('legacy values draft keeps old score baseline and can continue',t=>{const draft={schemaVersion:1,games:{values:{state:{phase:'pairs',selected:['Vabadus','Turvalisus'],roundPairs:[['Vabadus','Turvalisus'],['Vabadus','Turvalisus']],round:1,scores:{Vabadus:1,Turvalisus:0}}}}},a=app(t,{[DRAFT]:JSON.stringify(draft)},'#values');a.click('.choice');assert.equal(a.api.readDraftStore().games.values.state.scores.Vabadus,2);assert.equal(a.api.readDraftStore().games.values.state.baseRound,1)});
test('empty peak selectors do not create inferred themes; result survives refresh',t=>{let a=app(t,{},'#peak');assert.equal(a.d.querySelector('#pneed').value,'');assert.equal(a.d.querySelector('#pvalue').value,'');a.fill('#pmoment','Minu hetk');a.click('#pgo');a=app(t,a.snapshot(),'#peak');assert.ok(a.d.querySelector('#psave'));a.click('#psave');assert.equal(a.api.store().results[0].data.need,'');assert.equal(a.api.store().results[0].data.value,'')});
test('needs and values complete, edit a prior answer, save and reopen history',t=>{for(const id of ['needs','values']){const a=app(t,{},'#'+id);if(id==='needs'){a.click('#nstart');for(let i=0;i<a.api.NEED_QUESTIONS.length;i++)a.click('.choice');a.click('#nresultback');a.d.querySelectorAll('.choice')[1].click();a.click('#nsave');assert.equal(Object.values(a.api.store().results[0].data.scores).reduce((x,y)=>x+y,0),15)}else{[...a.d.querySelectorAll('[data-v]')].slice(0,8).forEach(b=>b.click());a.click('#vnext');for(let i=0;i<14;i++)a.click('.choice');a.fill('#vact','Tegevus');a.click('#vresultback');a.d.querySelectorAll('.choice')[1].click();assert.equal(a.d.querySelector('#vact').value,'Tegevus');a.click('#vsave');assert.equal(Object.values(a.api.store().results[0].data.scores).reduce((x,y)=>x+y,0),14)}a.api.renderModule('map');a.click('[data-view-result]');assert.ok(a.d.querySelector('.history-detail'))}});
test('all ten games can be opened consecutively without JS errors',t=>{const a=app(t);for(const id of ['wheel','needs','state','values','appreciation','dinner','greece','peak','pattern','knowme','map']){a.api.renderModule(id);assert.ok(a.d.querySelector('#module h1'));a.click('[data-back]')}assert.equal(a.api.store().results.length,0)});
test('localStorage denied leaves app interactive and never claims persistent save',t=>{const a=app(t);a.w.Storage.prototype.getItem=function(){throw Error('SecurityError')};a.w.Storage.prototype.setItem=function(){throw Error('SecurityError')};a.api.renderModule('pattern');a.fill('#pfact','ajutine');a.fill('#pstory','lugu');a.click('#pnext1');a.click('#pback2');assert.equal(a.d.querySelector('#pfact').value,'ajutine');assert.equal(a.api.saveResult('peak',{moment:'ajutine'}),false);assert.ok(a.d.querySelector('#storageWarning'));assert.doesNotMatch(a.d.querySelector('#toast').textContent,/Salvestatud sellesse seadmesse/)});
test('appreciation write failure cannot claim anonymous submission succeeded',t=>{const a=app(t,{},'#appreciation');a.fill('#anames','Mari\nJüri');a.click('#astart');a.click('[data-n]');a.fill('#a1','alles');a.w.Storage.prototype.setItem=function(){throw Error('quota')};a.click('#asend');assert.equal(a.d.querySelector('#a1').value,'alles');assert.doesNotMatch(a.d.querySelector('#toast').textContent,/Lisatud anonüümselt/)});
test('import rejects script-shaped objects, invalid names, state and schema types',t=>{const a=app(t),base={kind:'insight-games-user-data',app:'Insight Games',schemaVersion:3,completed:{schemaVersion:3,results:[result()]},drafts:{schemaVersion:2,games:{}}},variants=[{...base,schemaVersion:'3'},{...base,drafts:{schemaVersion:2,games:{knowme:{state:{names:['x'.repeat(2000),'Jüri']}}}}},{...base,drafts:{schemaVersion:2,games:{values:{state:{roundPairs:[['BAD','PAIR']]}}}}},{...base,completed:{schemaVersion:3,results:[result('wheel',{values:['<script>']})]}},JSON.parse(JSON.stringify(base).replace('"schemaVersion":3','"__proto__":{"polluted":true},"schemaVersion":3'))];const old=a.snapshot();for(const v of variants)assert.throws(()=>a.api.validateImportPayload(v));assert.deepEqual(a.snapshot(),old)});
test('actual FileReader import validates, asks consent and keeps existing ID collisions',async t=>{const a=app(t,{[STORE]:JSON.stringify({schemaVersion:3,results:[result()]})}),payload=JSON.parse(JSON.stringify(a.api.exportPayload()));payload.completed.results[0].data.moment='import ei tohi ajalugu üle kirjutada';payload.completed.results.push({...result(),id:'new-2'});const file=new a.w.File([JSON.stringify(payload)],'backup.json',{type:'application/json'});let confirms=0;a.w.confirm=()=>{confirms++;return true};a.api.importAllData(file);await new Promise(resolve=>setTimeout(resolve,50));assert.equal(confirms,1);assert.equal(a.api.store().results.length,2);assert.equal(a.api.store().results.find(r=>r.id==='old-1').data.moment,'vana tekst');const old=a.snapshot();a.api.importAllData(new a.w.File(['{not json'],'bad.json'));await new Promise(resolve=>setTimeout(resolve,50));assert.deepEqual(a.snapshot(),old);assert.match(a.d.querySelector('#toast').textContent,/Import ebaõnnestus/)});
test('legacy roulette seen questions and counters migrate without repetitions',t=>{const base=app(t),cat=Object.keys(base.api.DINNER)[0],seen=base.api.DINNER[cat].slice(0,3),a=app(t,{[DRAFT]:JSON.stringify({schemaVersion:1,games:{dinner:{state:{currentCat:cat,seen,current:{cat,q:seen[2]}}}}})},'#dinner');a.click('#dnew');assert.ok(!seen.includes(a.d.querySelector('#dq').textContent));assert.match(a.d.querySelector('#dseen').textContent,/^4 /)});
test('legacy invalid player names are preserved, not silently truncated or replaced',t=>{for(const id of ['knowme','appreciation']){const raw=JSON.stringify({schemaVersion:1,games:{[id]:{state:{names:['x'.repeat(2000),'Jüri'],phase:'choose',entries:[]}}}}),a=app(t,{[DRAFT]:raw},'#'+id);assert.equal(a.w.localStorage.getItem(DRAFT),raw);assert.match(a.d.querySelector('#module').textContent,/Mustand sisaldab nimesid/);assert.equal(a.d.querySelector('#kmstart,#astart'),null)}});
